- hosts: all
  remote_user: devops
  become: yes
  roles:
   - role: packages
     tags: ['pkg_install']
     pkg_list:
      - name: htop
        pkg_mgr: yum
        version: 
        state: latest

      - name: ['httpd', 'mod_ssl']
        pkg_mgr: yum
        version:
        state: present

      - name: mc
        pkg_mgr: yum
        version: -4.8.7
        state: present

     win_pkg_list:
      - name: notepadplusplus
        win_pkg_mgr: win_chocolatey
        version: -6.6
        state: present